name: Build and deploy Hugo site to GitHub Pages

on:
  push:
    # This GitHub Action is disabled. To enable it, comment the field branches-ignore and un-comment the field branches.
    # branches: [ 'main' ]
    branches-ignore: [ '**' ]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve the main branch
      uses: actions/checkout@v2
    - name: install hugo
      run: |
        sudo snap install hugo
    - name: fetch gh-pages branch into public directory
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: public
    - name: build static pages
      run: |
        hugo
    - name: push to gh-pages branch
      run: |
        cd public
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "generated"
        git push
